### ISSUE TITLE
if anyone else gets "pushd: no such file or directory: list" when doing "pu list"...

### ISSUE THREAD

**Issue by ym-han** [shawwn/tpudiepie#2]
I'm using zsh; I kept getting `pushd: no such file or directory: list` even after sudo installing this, but managed to fix it by adding an alias to my .zshrc: `alias pu='tpunicorn'`

Not sure why that was needed, but it looks like it works now; just posting about it for future users.

**Comment by shawwn** [comment]
Thank you! I'd be interested in steps to reproduce this problem, if you happen to have any. What OS are you running on?

**Comment by ym-han** [comment]
mac big sur

I do also have a bunch of CLI apps lying around, so it's quite possible that there was some kind of name conflict...? 

Haven't run into any issues so far with using the alias and simple `pu list`s though.
